In [36]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('TRADES_CopyTr_90D_ROI.csv')

In [3]:
data.head()

              Port_IDs                                      Trade_History
0  3925368433214965504  [{'time': 1718899656000, 'symbol': 'SOLUSDT', ...
1  4002413037164645377  [{'time': 1718980078000, 'symbol': 'NEARUSDT',...
2  3923766029921022977  [{'time': 1718677164000, 'symbol': 'ETHUSDT', ...
3  3994879592543698688  [{'time': 1718678214000, 'symbol': 'ETHUSDT', ...
4  3926423286576838657  [{'time': 1718979615000, 'symbol': 'ETHUSDT', ...

In [4]:
data['Trade_History'][0]

"[{'time': 1718899656000, 'symbol': 'SOLUSDT', 'side': 'BUY', 'price': 132.537, 'fee': -0.9940275, 'feeAsset': 'USDT', 'quantity': 1988.055, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'SOL', 'qty': 15.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718899618000, 'symbol': 'DOGEUSDT', 'side': 'BUY', 'price': 0.12182, 'fee': -0.27979617, 'feeAsset': 'USDT', 'quantity': 1398.98088, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'DOGE', 'qty': 11484.0, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718899618000, 'symbol': 'DOGEUSDT', 'side': 'BUY', 'price': 0.12182, 'fee': -0.03949404, 'feeAsset': 'USDT', 'quantity': 197.47022, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'DOGE', 'qty': 1621.0, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718899616000, 'symbol': 'DOGEUSDT', 'side': 'BUY', 'price': 0.12182, 'fee': -0.00828375, 'feeAsset': 'USDT', 'quantity': 16.56752, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'DOGE', 'qty': 136.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718899616000, 'symbol': 'DOGEUSDT', 'side': 'BUY', 'price': 0.12182, 'fee': -0.04610887, 'feeAsset': 'USDT', 'quantity': 92.21774, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'DOGE', 'qty': 757.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718899616000, 'symbol': 'DOGEUSDT', 'side': 'BUY', 'price': 0.12182, 'fee': -0.12571824, 'feeAsset': 'USDT', 'quantity': 251.43648, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'DOGE', 'qty': 2064.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718899616000, 'symbol': 'DOGEUSDT', 'side': 'BUY', 'price': 0.12182, 'fee': -0.02180578, 'feeAsset': 'USDT', 'quantity': 43.61156, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'DOGE', 'qty': 358.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718899607000, 'symbol': 'SOLUSDT', 'side': 'BUY', 'price': 132.585, 'fee': -0.159102, 'feeAsset': 'USDT', 'quantity': 795.51, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'SOL', 'qty': 6.0, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718899607000, 'symbol': 'SOLUSDT', 'side': 'BUY', 'price': 132.585, 'fee': -0.5966325, 'feeAsset': 'USDT', 'quantity': 1193.265, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'SOL', 'qty': 9.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718889684000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.454, 'fee': -0.3485255, 'feeAsset': 'USDT', 'quantity': 697.051, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 156.5, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718889684000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.454, 'fee': -0.0031178, 'feeAsset': 'USDT', 'quantity': 6.2356, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 1.4, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718889684000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.454, 'fee': -0.13361999, 'feeAsset': 'USDT', 'quantity': 267.24, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 60.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718889684000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.454, 'fee': -0.5146597, 'feeAsset': 'USDT', 'quantity': 1029.3194, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 231.1, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718889588000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.471, 'fee': -0.16565055, 'feeAsset': 'USDT', 'quantity': 331.3011, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 74.1, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718889588000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.471, 'fee': -0.13413, 'feeAsset': 'USDT', 'quantity': 268.26, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 60.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718889588000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.471, 'fee': -0.67065, 'feeAsset': 'USDT', 'quantity': 1341.3, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 300.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718889588000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.471, 'fee': -0.0295086, 'feeAsset': 'USDT', 'quantity': 59.0172, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 13.2, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.525, 'fee': -0.01925212, 'feeAsset': 'USDT', 'quantity': 38.50425, 'quantityAsset': 'USDT', 'realizedProfit': 1.33256281, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 1.57, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.525, 'fee': -0.100062, 'feeAsset': 'USDT', 'quantity': 200.124, 'quantityAsset': 'USDT', 'realizedProfit': 6.92593156, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 8.16, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.525, 'fee': -0.25751249, 'feeAsset': 'USDT', 'quantity': 515.025, 'quantityAsset': 'USDT', 'realizedProfit': 17.82408858, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 21.0, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.526, 'fee': -0.10006608, 'feeAsset': 'USDT', 'quantity': 200.13216, 'quantityAsset': 'USDT', 'realizedProfit': 6.93409156, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 8.16, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.526, 'fee': -0.20000953, 'feeAsset': 'USDT', 'quantity': 400.01906, 'quantityAsset': 'USDT', 'realizedProfit': 13.85968547, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 16.31, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.526, 'fee': -0.10006608, 'feeAsset': 'USDT', 'quantity': 200.13216, 'quantityAsset': 'USDT', 'realizedProfit': 6.93409156, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 8.16, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.526, 'fee': -0.3347799, 'feeAsset': 'USDT', 'quantity': 669.5598, 'quantityAsset': 'USDT', 'realizedProfit': 23.19861516, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 27.3, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.526, 'fee': -0.01508349, 'feeAsset': 'USDT', 'quantity': 30.16698, 'quantityAsset': 'USDT', 'realizedProfit': 1.04521233, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 1.23, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.526, 'fee': -0.01508349, 'feeAsset': 'USDT', 'quantity': 30.16698, 'quantityAsset': 'USDT', 'realizedProfit': 1.04521233, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 1.23, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.10007016, 'feeAsset': 'USDT', 'quantity': 200.14032, 'quantityAsset': 'USDT', 'realizedProfit': 6.94225156, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 8.16, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.10007016, 'feeAsset': 'USDT', 'quantity': 200.14032, 'quantityAsset': 'USDT', 'realizedProfit': 6.94225156, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 8.16, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.20001768, 'feeAsset': 'USDT', 'quantity': 400.03537, 'quantityAsset': 'USDT', 'realizedProfit': 13.87599547, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 16.31, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.02930976, 'feeAsset': 'USDT', 'quantity': 58.61953, 'quantityAsset': 'USDT', 'realizedProfit': 2.03333103, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 2.39, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.03544151, 'feeAsset': 'USDT', 'quantity': 70.88303, 'quantityAsset': 'USDT', 'realizedProfit': 2.45871409, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 2.89, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.03544151, 'feeAsset': 'USDT', 'quantity': 70.88303, 'quantityAsset': 'USDT', 'realizedProfit': 2.45871409, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 2.89, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.01410302, 'feeAsset': 'USDT', 'quantity': 28.20605, 'quantityAsset': 'USDT', 'realizedProfit': 0.97838104, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 1.15, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.2918713, 'feeAsset': 'USDT', 'quantity': 583.7426, 'quantityAsset': 'USDT', 'realizedProfit': 20.24823373, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 23.8, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.16273664, 'feeAsset': 'USDT', 'quantity': 325.47329, 'quantityAsset': 'USDT', 'realizedProfit': 11.28966645, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 13.27, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.01005607, 'feeAsset': 'USDT', 'quantity': 20.11214, 'quantityAsset': 'USDT', 'realizedProfit': 0.69762822, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 0.82, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.527, 'fee': -0.39059247, 'feeAsset': 'USDT', 'quantity': 781.18495, 'quantityAsset': 'USDT', 'realizedProfit': 27.09690102, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 31.85, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.528, 'fee': -0.10007424, 'feeAsset': 'USDT', 'quantity': 200.14848, 'quantityAsset': 'USDT', 'realizedProfit': 6.95041156, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 8.16, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.528, 'fee': -0.10007424, 'feeAsset': 'USDT', 'quantity': 200.14848, 'quantityAsset': 'USDT', 'realizedProfit': 6.95041156, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 8.16, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.528, 'fee': -0.01508472, 'feeAsset': 'USDT', 'quantity': 30.16944, 'quantityAsset': 'USDT', 'realizedProfit': 1.04767233, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 1.23, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.528, 'fee': -0.14913024, 'feeAsset': 'USDT', 'quantity': 298.26048, 'quantityAsset': 'USDT', 'realizedProfit': 10.35747605, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 12.16, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.528, 'fee': -0.3348072, 'feeAsset': 'USDT', 'quantity': 669.6144, 'quantityAsset': 'USDT', 'realizedProfit': 23.25321516, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 27.3, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.528, 'fee': -0.0741972, 'feeAsset': 'USDT', 'quantity': 148.3944, 'quantityAsset': 'USDT', 'realizedProfit': 5.15318504, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 6.05, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.529, 'fee': -0.01508533, 'feeAsset': 'USDT', 'quantity': 30.17067, 'quantityAsset': 'USDT', 'realizedProfit': 1.04890233, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 1.23, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.529, 'fee': -0.06770004, 'feeAsset': 'USDT', 'quantity': 135.40008, 'quantityAsset': 'USDT', 'realizedProfit': 4.707269, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 5.52, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718874124000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.529, 'fee': -0.0662283, 'feeAsset': 'USDT', 'quantity': 132.4566, 'quantityAsset': 'USDT', 'realizedProfit': 4.60493706, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 5.4, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718873009000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.20511672, 'feeAsset': 'USDT', 'quantity': 1025.5836, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 225.8, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718873009000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.02761536, 'feeAsset': 'USDT', 'quantity': 138.0768, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 30.4, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.06813, 'feeAsset': 'USDT', 'quantity': 136.26, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 30.0, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.2843292, 'feeAsset': 'USDT', 'quantity': 568.6584, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 125.2, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.0111279, 'feeAsset': 'USDT', 'quantity': 22.2558, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 4.9, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.0084027, 'feeAsset': 'USDT', 'quantity': 16.8054, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 3.7, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.7975752, 'feeAsset': 'USDT', 'quantity': 1595.1504, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 351.2, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.0027252, 'feeAsset': 'USDT', 'quantity': 5.4504, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 1.2, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.14261879, 'feeAsset': 'USDT', 'quantity': 285.2376, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 62.8, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.0233913, 'feeAsset': 'USDT', 'quantity': 46.7826, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 10.3, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.0036336, 'feeAsset': 'USDT', 'quantity': 7.2672, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 1.6, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718873005000, 'symbol': 'FILUSDT', 'side': 'BUY', 'price': 4.542, 'fee': -0.07607849, 'feeAsset': 'USDT', 'quantity': 152.157, 'quantityAsset': 'USDT', 'realizedProfit': 0.0, 'realizedProfitAsset': 'USDT', 'baseAsset': 'FIL', 'qty': 33.5, 'positionSide': 'LONG', 'activeBuy': True}, {'time': 1718868187000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.622, 'fee': -0.04222673, 'feeAsset': 'USDT', 'quantity': 84.45346, 'quantityAsset': 'USDT', 'realizedProfit': 3.2439778, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 3.43, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718868187000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.622, 'fee': -0.20029997, 'feeAsset': 'USDT', 'quantity': 400.59994, 'quantityAsset': 'USDT', 'realizedProfit': 15.38761482, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 16.27, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718868187000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.622, 'fee': -0.677105, 'feeAsset': 'USDT', 'quantity': 1354.21, 'quantityAsset': 'USDT', 'realizedProfit': 52.01713678, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 55.0, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718868187000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.622, 'fee': -0.1908205, 'feeAsset': 'USDT', 'quantity': 381.641, 'quantityAsset': 'USDT', 'realizedProfit': 14.65937491, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 15.5, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718868187000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.622, 'fee': -0.01009502, 'feeAsset': 'USDT', 'quantity': 20.19004, 'quantityAsset': 'USDT', 'realizedProfit': 0.77552822, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 0.82, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718868187000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.622, 'fee': -0.01501942, 'feeAsset': 'USDT', 'quantity': 30.03884, 'quantityAsset': 'USDT', 'realizedProfit': 1.15383467, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 1.22, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718868187000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.622, 'fee': -0.01501942, 'feeAsset': 'USDT', 'quantity': 30.03884, 'quantityAsset': 'USDT', 'realizedProfit': 1.15383467, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 1.22, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718868187000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.623, 'fee': -0.31468194, 'feeAsset': 'USDT', 'quantity': 629.36388, 'quantityAsset': 'USDT', 'realizedProfit': 24.19934211, 'realizedProfitAsset': 'USDT', 'baseAsset': 'ETC', 'qty': 25.56, 'positionSide': 'LONG', 'activeBuy': False}, {'time': 1718868187000, 'symbol': 'ETCUSDT', 'side': 'SELL', 'price': 24.623, 'fee': -0.2003081, 'feeAsset': 'USDT', 'quantity': 400.61621, 'quantityAsset': 'USDT', 'realizedProfit': 15.40388482, 'realiz

In [5]:
data.isnull().sum()

Port_IDs         0
Trade_History    1
dtype: int64

In [7]:
data.shape

(150, 2)

In [8]:
data.tail()

                Port_IDs                                      Trade_History
145  4000222729738650369  [{'time': 1718982068000, 'symbol': 'ARKMUSDT',...
146  3998659472131949824  [{'time': 1718979385000, 'symbol': 'BTCUSDT', ...
147  4028701921959171840  [{'time': 1718984241000, 'symbol': 'BTCUSDT', ...
148  4014818740371615232  [{'time': 1718983357000, 'symbol': 'SOLUSDT', ...
149  3768170840939476993  [{'time': 1718977395000, 'symbol': 'BNBUSDT', ...

In [9]:
data['Trade_History'] = data['Trade_History'].fillna('[]')

In [10]:
data.isnull().sum()

Port_IDs         0
Trade_History    0
dtype: int64

In [11]:
import ast

In [12]:
data['Trade_History'] = data['Trade_History'].apply(ast.literal_eval)

In [16]:
trades = pd.json_normalize(data.to_dict(orient='records'), 
                            record_path='Trade_History', 
                            meta=['Port_IDs'])

In [17]:
trades.head()

,time,symbol,side,price,fee,feeAsset,quantity,quantityAsset,realizedProfit,realizedProfitAsset,baseAsset,qty,positionSide,activeBuy,Port_IDs
0,1718899656000,SOLUSDT,BUY,132.53700,-0.994027,USDT,1988.05500,USDT,0.0,USDT,SOL,15.0,LONG,True,3925368433214965504
1,1718899618000,DOGEUSDT,BUY,0.12182,-0.279796,USDT,1398.98088,USDT,0.0,USDT,DOGE,11484.0,LONG,False,3925368433214965504
2,1718899618000,DOGEUSDT,BUY,0.12182,-0.039494,USDT,197.47022,USDT,0.0,USDT,DOGE,1621.0,LONG,False,3925368433214965504
3,1718899616000,DOGEUSDT,BUY,0.12182,-0.008284,USDT,16.56752,USDT,0.0,USDT,DOGE,136.0,LONG,True,3925368433214965504
4,1718899616000,DOGEUSDT,BUY,0.12182,-0.046109,USDT,92.21774,USDT,0.0,USDT,DOGE,757.0,LONG,True,3925368433214965504

In [18]:
df = trades.copy()

In [19]:
trades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211277 entries, 0 to 211276
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   time                 211277 non-null  int64
 1   symbol               211277 non-null  object
 2   side                 211277 non-null  object
 3   price                211277 non-null  float64
 4   fee                  211277 non-null  float64
 5   feeAsset             211277 non-null  object
 6   quantity             211277 non-null  float64
 7   quantityAsset        211277 non-null  object
 8   realizedProfit       211277 non-null  float64
 9   realizedProfitAsset  211277 non-null  object
 10  baseAsset            211277 non-null  object
 11  qty                  211277 non-null  float64
 12  positionSide         211277 non-null  object
 13  activeBuy            211277 non-null  bool
 14  Port_IDs             211277 non-null  object
dtypes: bool(1), float64(5), int64(1), object(8)
memory usage: 22.8+ MB

In [20]:
df.isnull().sum()

time                   0
symbol                 0
side                   0
price                  0
fee                    0
feeAsset               0
quantity               0
quantityAsset          0
realizedProfit         0
realizedProfitAsset    0
baseAsset              0
qty                    0
positionSide           0
activeBuy              0
Port_IDs               0
dtype: int64

In [23]:
df.duplicated().sum()

0

In [22]:
df.drop_duplicates(inplace=True)

In [24]:
df.shape

(200026, 15)

In [25]:
df['time'] = pd.to_datetime(df['time'], unit='ms')

In [26]:
df.head()

,time,symbol,side,price,fee,feeAsset,quantity,quantityAsset,realizedProfit,realizedProfitAsset,baseAsset,qty,positionSide,activeBuy,Port_IDs
0,2024-06-20 16:07:36,SOLUSDT,BUY,132.53700,-0.994027,USDT,1988.05500,USDT,0.0,USDT,SOL,15.0,LONG,True,3925368433214965504
1,2024-06-20 16:06:58,DOGEUSDT,BUY,0.12182,-0.279796,USDT,1398.98088,USDT,0.0,USDT,DOGE,11484.0,LONG,False,3925368433214965504
2,2024-06-20 16:06:58,DOGEUSDT,BUY,0.12182,-0.039494,USDT,197.47022,USDT,0.0,USDT,DOGE,1621.0,LONG,False,3925368433214965504
3,2024-06-20 16:06:56,DOGEUSDT,BUY,0.12182,-0.008284,USDT,16.56752,USDT,0.0,USDT,DOGE,136.0,LONG,True,3925368433214965504
4,2024-06-20 16:06:56,DOGEUSDT,BUY,0.12182,-0.046109,USDT,92.21774,USDT,0.0,USDT,DOGE,757.0,LONG,True,3925368433214965504

### ROI

In [27]:
account_pnl = df.groupby('Port_IDs')['realizedProfit'].sum().reset_index()
account_pnl.rename(columns={'realizedProfit': 'Total_PnL'}, inplace=True)

In [28]:
investment = df.groupby('Port_IDs')['quantity'].sum().reset_index().rename(columns={'quantity': 'Total_Investment'})

In [30]:
roi_df = pd.merge(account_pnl, investment, on='Port_IDs')
roi_df['ROI'] = (roi_df['Total_PnL'] / roi_df['Total_Investment']) * 100
roi_df[['Port_IDs', 'ROI']]

                Port_IDs       ROI
0    3672754654734989568  0.480363
1    3733192481840423936  0.232470
2    3768170840939476993  8.779089
3    3784403294629753856  0.340279
4    3786761687746711808  0.282980
..                   ...       ...
144  4039279455324236544  1.027423
145  4040382575336130560  0.000000
146  4040843843196854529  0.965300
147  4041804592937345281 -0.142773
148  4041860229502600193  1.349300

[149 rows x 2 columns]

### Trade Type

In [32]:
def classify_trade(row):
    if row['side'] == 'BUY' and row['positionSide'] == 'LONG':
        return 'long_open' if row['activeBuy'] else 'long_close'
    
    return 'other'

df['tradeType'] = df.apply(classify_trade, axis=1)
df[['side', 'positionSide', 'activeBuy', 'tradeType']]

        side positionSide  activeBuy   tradeType
0        BUY         LONG       True   long_open
1        BUY         LONG      False  long_close
2        BUY         LONG      False  long_close
3        BUY         LONG       True   long_open
4        BUY         LONG       True   long_open
...      ...          ...        ...         ...
211272  SELL         BOTH      False       other
211273  SELL         BOTH      False       other
211274  SELL         BOTH      False       other
211275  SELL         BOTH      False       other
211276  SELL         BOTH      False       other

[200026 rows x 4 columns]

### Profit and Loss

In [33]:
account_pnl = df.groupby('Port_IDs')['realizedProfit'].sum().reset_index()
account_pnl.rename(columns={'realizedProfit': 'Total_PnL'}, inplace=True)
account_pnl

                Port_IDs    Total_PnL
0    3672754654734989568   565.547761
1    3733192481840423936  2653.591900
2    3768170840939476993   243.668899
3    3784403294629753856  2493.618898
4    3786761687746711808   170.220200
..                   ...          ...
144  4039279455324236544  1023.498387
145  4040382575336130560     0.000000
146  4040843843196854529  2043.478100
147  4041804592937345281  -796.682686
148  4041860229502600193  2327.336000

[149 rows x 2 columns]

### Win Rate, Win Positions, Total Position

In [34]:
# Total positions per account
total_positions = df.groupby('Port_IDs').size().reset_index(name='Total_Positions')

# Count winning positions 
win_positions = df[df['realizedProfit'] > 0].groupby('Port_IDs').size().reset_index(name='Winning_Positions')

# Merge and compute win rate 
account_stats = pd.merge(total_positions, win_positions, on='Port_IDs', how='left').fillna(0)
account_stats['Win_Rate'] = (account_stats['Winning_Positions'] / account_stats['Total_Positions']) * 100
account_stats

                Port_IDs  Total_Positions  Winning_Positions   Win_Rate
0    3672754654734989568              461              206.0  44.685466
1    3733192481840423936              585              457.0  78.119658
2    3768170840939476993               14                6.0  42.857143
3    3784403294629753856             5833             1767.0  30.293160
4    3786761687746711808               79               34.0  43.037975
..                   ...              ...                ...        ...
144  4039279455324236544              310              171.0  55.161290
145  4040382575336130560               70                0.0   0.000000
146  4040843843196854529               48               13.0  27.083333
147  4041804592937345281              330               75.0  22.727273
148  4041860229502600193               95               38.0  40.000000

[149 rows x 4 columns]

### Sharpe_Ratio

In [37]:
# Compute a simple return for each trade
df['trade_return'] = df['realizedProfit'] / df['quantity']

# For eahc account, compute the average return and deviation of returns 
def compute_sharpe(x, rf=0.0):
    avg_return = np.mean(x)
    std_return = np.std(x)
    return (avg_return - rf) / std_return if std_return != 0 else 0

sharpe_df = df.groupby('Port_IDs')['trade_return'].agg(lambda x: compute_sharpe(x)).reset_index(name='Sharpe_Ratio')
sharpe_df

                Port_IDs  Sharpe_Ratio
0    3672754654734989568      0.297253
1    3733192481840423936      0.863606
2    3768170840939476993      0.866019
3    3784403294629753856      0.218097
4    3786761687746711808      0.503104
..                   ...           ...
144  4039279455324236544      1.098484
145  4040382575336130560      0.000000
146  4040843843196854529      0.600050
147  4041804592937345281     -0.411003
148  4041860229502600193      0.809067

[149 rows x 2 columns]

### MDD

In [38]:
def calculate_mdd(pnl_series):
    cum_pnl = pnl_series.cumsum()
    running_max = cum_pnl.cummax()
    drawdown = running_max - cum_pnl
    return drawdown.max()


# For each account, sort trades by time and compute MDD: 
mdd_list = []
for pid, group in df.groupby('Port_IDs'):
    group_sorted = group.sort_values('time')
    mdd = calculate_mdd(group_sorted['realizedProfit'])
    mdd_list.append({'Port_IDs': pid, 'MDD': mdd})
    
mdd_df = pd.DataFrame(mdd_list)
mdd_df

                Port_IDs          MDD
0    3672754654734989568    80.917805
1    3733192481840423936  2743.120000
2    3768170840939476993     0.000000
3    3784403294629753856   271.053818
4    3786761687746711808   123.460267
..                   ...          ...
144  4039279455324236544     0.000000
145  4040382575336130560     0.000000
146  4040843843196854529     0.000000
147  4041804592937345281  1000.390612
148  4041860229502600193     0.000000

[149 rows x 2 columns]

### Top 20

In [44]:
# Merge the computed metrics 
metrics_df = account_pnl.merge(roi_df[['Port_IDs', 'ROI']], on='Port_IDs') \
                        .merge(sharpe_df, on='Port_IDs') \
                        .merge(mdd_df, on='Port_IDs') \
                        .merge(account_stats[['Port_IDs', 'Win_Rate', 'Winning_Positions', 'Total_Positions']], on='Port_IDs')
                        
# Define weights for each metric 
weights = {
    'ROI' : 0.3,
    'Sharpe_Ratio': 0.3,
    'Win_Rate': 0.2,
    'Total_PnL': 0.2,
}

# Normalize or scale metrics as necessary before combining
# For simplicity, assume metrics are on a comparable scale. 

metrics_df['Composite_Score'] = (
    weights['ROI'] * metrics_df['ROI'] +
    weights['Sharpe_Ratio'] * metrics_df['Sharpe_Ratio'] +
    weights['Win_Rate'] * (metrics_df['Win_Rate'] * 100) +
    weights['Total_PnL'] * metrics_df['Total_PnL']
)

# Rank accounts by the composite score 
metrics_df['Rank'] = metrics_df['Composite_Score'].rank(ascending=False)
metrics_df.sort_values('Rank').head(20)

,Port_IDs,Total_PnL,ROI,Sharpe_Ratio,MDD,Win_Rate,Winning_Positions,Total_Positions,Composite_Score,Rank
96,4020204877254599680,70638.371244,0.314421,-0.099254,21232.442005,32.725974,1832.0,5598,14782.258270,1.0
75,3999240873283311617,42220.472165,0.544322,0.587686,300.813848,52.093342,2277.0,4371,9486.300885,2.0
98,4021669203289716224,26438.767142,0.407462,0.037703,2533.341164,31.621287,511.0,1616,5920.312721,3.0
50,3960874214179953664,19277.539253,0.232661,0.100948,2234.000000,50.605110,1129.0,2231,4867.710130,4.0
62,3986814617275053313,15847.596344,0.859710,1.278991,2.381947,77.905605,2641.0,3390,4728.272974,5.0
17,3907081197088384000,16986.456333,1.056086,0.774123,2062.986725,60.946596,2408.0,3951,4616.772245,6.0
48,3956076827719377409,16618.829175,1.032787,0.676194,635.050015,51.213149,1963.0,3833,4348.541509,7.0
107,4028701921959171840,15750.621514,0.384287,0.641731,356.299950,50.084602,296.0,591,4152.124155,8.0
99,4022565861939831809,13807.949797,0.233892,0.595924,385.075554,52.614897,332.0,631,3814.136844,9.0
5,3788465932399412480,13209.206074,0.823698,0.364734,1772.219440,45.270025,1249.0,2759,3547.598252,10.0
32,3939318616482048768,9406.865606,1.012116,0.790024,87.003360,57.368421,109.0,190,3029.282184,11.0
63,3987739404272887297,12435.873935,0.571869,0.155738,3267.267922,23.159753,1312.0,5665,2950.588127,12.0
84,4008711265867865600,10579.778143,0.293362,0.649598,509.550000,40.771350,148.0,363,2931.665514,13.0
14,3886752488982104320,7122.138782,0.897133,0.584098,38.208100,74.792013,899.0,1202,2920.712392,14.0
27,3931992636670880512,10169.889442,0.570859,0.466115,1651.131700,40.373766,2290.0,5672,2841.764298,15.0
30,3936410995029308417,10681.514000,1.791634,0.617086,0.000000,31.578947,6.0,19,2768.604363,16.0
73,3998572645139652353,9432.841264,0.462755,0.413249,214.715155,34.817814,86.0,247,2583.187329,17.0
125,4031493134338259457,8887.173793,0.117254,0.071045,3584.894436,37.889688,632.0,1668,2535.285013,18.0
37,3944088772635000577,7471.568979,0.709913,0.444498,96.057388,46.050594,2676.0,5811,2415.671993,19.0
51,3962024093501274881,9417.353594,0.149626,0.066348,1793.869639,25.688889,289.0,1125,2397.313289,20.0

In [43]:
metrics_df

,Port_IDs,Total_PnL,ROI,Sharpe_Ratio,MDD,Win_Rate,Winning_Positions,Total_Positions
0,3672754654734989568,565.547761,0.480363,0.297253,80.917805,44.685466,206.0,461
1,3733192481840423936,2653.591900,0.232470,0.863606,2743.120000,78.119658,457.0,585
2,3768170840939476993,243.668899,8.779089,0.866019,0.000000,42.857143,6.0,14
3,3784403294629753856,2493.618898,0.340279,0.218097,271.053818,30.293160,1767.0,5833
4,3786761687746711808,170.220200,0.282980,0.503104,123.460267,43.037975,34.0,79
...,...,...,...,...,...,...,...,...
144,4039279455324236544,1023.498387,1.027423,1.098484,0.000000,55.161290,171.0,310
145,4040382575336130560,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,70
146,4040843843196854529,2043.478100,0.965300,0.600050,0.000000,27.083333,13.0,48
147,4041804592937345281,-796.682686,-0.142773,-0.411003,1000.390612,22.727273,75.0,330
148,4041860229502600193,2327.336000,1.349300,0.809067,0.000000,40.000000,38.0,95